version: '3.8'

services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: uname
        POSTGRES_DB: dbname
        POSTGRES_PASSWORD: pwd
      ports:
        - "5432:5432"
      volumes:
        - db-data: path
  redis:
      image: redis:latest
      container_name: redis_server
      ports:
        - "6379:6379"
        

volumes:
  db-data: 